# Generated by Django 3.2.7 on 2021-10-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrador',
            table='administrador',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
