# Generated by Django 3.2.8 on 2021-10-22 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano_lancamento', models.IntegerField()),
                ('nome_diretor', models.CharField(max_length=200)),
                ('audio', models.CharField(max_length=50)),
                ('legenda', models.CharField(max_length=50)),
                ('poster_img', models.ImageField(upload_to='images/')),
                ('duracao_min', models.IntegerField()),
                ('elenco', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('sinopse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_assentos', models.IntegerField(default=0)),
                ('saida_emergencia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Exibicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('codigo_filme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.filme')),
                ('codigo_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('artigo_img', models.ImageField(upload_to='images/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.administrador')),
            ],
        ),
    ]
