# Generated by Django 3.2.7 on 2021-10-05 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano_lancamento', models.IntegerField(default=1895)),
                ('nome_diretor', models.CharField(max_length=200)),
                ('audio', models.CharField(max_length=50)),
                ('legenda', models.CharField(max_length=50)),
                ('poster_img', models.BinaryField()),
                ('duracao_min', models.IntegerField(default=60)),
                ('elenco', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('sinopse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exibicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('codigo_administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.administrador')),
                ('codigo_filme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.filme')),
                ('codigo_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.sala')),
            ],
        ),
    ]
