# Generated by Django 3.2.7 on 2021-10-27 17:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do cinema')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('numero', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('codigo_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.administrador', verbose_name='Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Exibicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(max_length=50, verbose_name='Áudio')),
                ('legenda', models.CharField(max_length=50, verbose_name='Legenda')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data de exibição')),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='Início da exibição')),
                ('codigo_cinema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do filme')),
                ('ano_lancamento', models.IntegerField(verbose_name='Ano de lançamento')),
                ('nome_diretor', models.CharField(max_length=200, verbose_name='Nome do diretor')),
                ('poster_img', models.ImageField(upload_to='images/', verbose_name='Imagem do filme')),
                ('poster_img_blob', models.BinaryField()),
                ('duracao_min', models.IntegerField(verbose_name='Duração em minutos')),
                ('elenco', models.CharField(max_length=100, verbose_name='Elenco')),
                ('genero', models.CharField(max_length=50, verbose_name='Genero')),
                ('sinopse', models.CharField(max_length=200, verbose_name='Sinopse')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_assentos', models.IntegerField(default=0)),
                ('sessao_3d', models.BooleanField()),
                ('sessao_normal', models.BooleanField()),
                ('sessao_platinum', models.BooleanField()),
                ('codigo_cinema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da reserva')),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='Horário da reserva')),
                ('codigo_administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.administrador', verbose_name='Administrador')),
                ('codigo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.cliente', verbose_name='Cliente')),
                ('codigo_exibicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.exibicao', verbose_name='Exibição')),
            ],
        ),
        migrations.AddField(
            model_name='exibicao',
            name='codigo_filme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.filme'),
        ),
        migrations.AddField(
            model_name='exibicao',
            name='codigo_sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.sala'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('comentario', models.TextField()),
                ('codigo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.cliente', verbose_name='Cliente')),
                ('codigo_filme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.filme', verbose_name='Filme')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('texto', models.TextField()),
                ('artigo_img', models.ImageField(upload_to='images/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.administrador', verbose_name='Autor')),
            ],
        ),
    ]
