# Generated by Django 3.2.7 on 2021-10-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='numero_assentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sala',
            name='saida_emergencia',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filme',
            name='ano_lancamento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filme',
            name='duracao_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filme',
            name='poster_img',
            field=models.CharField(max_length=200),
        ),
    ]
