# Generated by Django 3.2.7 on 2021-10-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.CharField(max_length=2000, verbose_name='Sinopse'),
        ),
    ]
