# Generated by Django 3.2.7 on 2021-10-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='poster_img_blob',
            field=models.BinaryField(),
        ),
    ]
