# Generated by Django 3.2.7 on 2021-10-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filme',
            table='Filme',
        ),
    ]
