# Generated by Django 3.2.8 on 2021-10-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste',
        ),
    ]
