# Generated by Django 3.2.7 on 2021-10-27 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_alter_filme_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='exibicao',
            name='codigo_cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.cinema', verbose_name='Cinema'),
        ),
        migrations.AlterField(
            model_name='exibicao',
            name='codigo_filme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.filme', verbose_name='Filme'),
        ),
        migrations.AlterField(
            model_name='exibicao',
            name='codigo_sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.sala', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='codigo_cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.cinema', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero_assentos',
            field=models.IntegerField(default=0, verbose_name='Número de assentos'),
        ),
        migrations.AlterModelTable(
            name='artigo',
            table='Artigo',
        ),
        migrations.AlterModelTable(
            name='avaliacao',
            table='Avaliacao',
        ),
        migrations.AlterModelTable(
            name='cinema',
            table='Cinema',
        ),
        migrations.AlterModelTable(
            name='exibicao',
            table='Exibicao',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='Reserva',
        ),
        migrations.AlterModelTable(
            name='sala',
            table='Sala',
        ),
    ]
