# Generated by Django 3.2.8 on 2021-10-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_alter_assento_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assento',
            table='assento',
        ),
    ]
