# Generated by Django 3.2.8 on 2021-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_auto_20211027_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='sessao_3d',
            field=models.BooleanField(verbose_name='Sessão em 3D'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='sessao_normal',
            field=models.BooleanField(verbose_name='Sessão Normal'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='sessao_platinum',
            field=models.BooleanField(verbose_name='Sessão Platinum'),
        ),
    ]
