# Generated by Django 3.2.8 on 2021-10-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_auto_20211027_1607'),
        ('cinema_app', '0004_auto_20211027_1611'),
    ]

    operations = [
    ]
