# Generated by Django 3.2.7 on 2021-10-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_remove_exibicao_codigo_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='poster_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
