# Generated by Django 3.2.8 on 2021-10-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_assento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assento',
            table='assento',
        ),
    ]
