# Generated by Django 3.2.7 on 2021-10-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_auto_20211019_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='ano_lancamento',
            field=models.IntegerField(verbose_name='Ano de lançamento'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='duracao_min',
            field=models.IntegerField(verbose_name='Duração em minutos'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='elenco',
            field=models.CharField(max_length=100, verbose_name='Elenco Principal'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(max_length=50, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do filme'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='nome_diretor',
            field=models.CharField(max_length=200, verbose_name='Nome do Diretor'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='poster_img',
            field=models.CharField(max_length=200, verbose_name='Imagem do pôster'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.CharField(max_length=200, verbose_name='Sinopse'),
        ),
    ]
