# Generated by Django 3.2.8 on 2021-10-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0007_alter_assento_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assento',
            name='fileira',
            field=models.IntegerField(),
        ),
    ]
