# Generated by Django 3.2.8 on 2021-10-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0008_alter_assento_fileira'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assento',
            table='asento',
        ),
    ]
