# Generated by Django 3.2.8 on 2021-10-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0010_alter_assento_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assento',
        ),
    ]
