# Generated by Django 3.2.8 on 2021-10-28 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('cinema_app', '0013_delete_assento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileira', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('adaptado', models.BooleanField(verbose_name='Adaptado')),
                ('estado_conservacao', models.CharField(max_length=100, verbose_name='Conservação')),
                ('codigo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.cliente', verbose_name='Reservado')),
                ('codigo_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_app.sala', verbose_name='Sala')),
            ],
            options={
                'db_table': 'assento',
            },
        ),
    ]
